<!--<section id="fmsgs">
    <div class="row">
        <div class="span10">
            <div class="alert-message warning fade in">
                <a href="#" class="close">×</a>
                <p><strong>Holy guacamole!</strong> Best check yo self, you’re not <a href="#">looking too good</a>.</p>
            </div>            
            <div class="alert-message error fade in">
                <a href="#" class="close">×</a>
                <p><strong>Holy guacamole!</strong> Best check yo self, you’re not <a href="#">looking too good</a>.</p>
            </div>            
            <div class="alert-message success fade in">
                <a href="#" class="close">×</a>
                <p><strong>Holy guacamole!</strong> Best check yo self, you’re not <a href="#">looking too good</a>.</p>
            </div>            
            <div class="alert-message info fade in">
                <a href="#" class="close">×</a>
                <p><strong>Holy guacamole!</strong> Best check yo self, you’re not <a href="#">looking too good</a>.</p>
            </div>            
        </div>
    </div>
</section>
-->