<html> 
<body>
<table cellpadding=0 cellspacing=0 width="580px" align=center style="border:#cccccc 1px solid"><tr><td>
<table cellpadding=0 cellspacing=0 width="94%" align=center>
<tr><td><p style="font-size=10px; margin:15px 0 10px; text-align:justify">Para asegurar la entrega de nuestros e-mail en su correo, por favor agregue <a style="color:#3366ff" href="mailto:notificaciones@app">notificaciones@app</a> a su libreta de contactos
Si no visualiza bien este correo electrónico, haga <a style="color:#3366ff" href="http://" target="_blank">click aquí</a>. </p>
</td></tr>
<tr><td height=80px><img src="<?=MEDIA_URL?>/images/emailing/logo.png" alt="logo app" border=0 height=50px></td></tr>
<tr><td style="text-align:justify;font-family:verdana;font-size=12px">

<?=$this->emailTemplate?>

<br>
<b>El equipo</b>
<br><br>
</td></tr></table>
</td></tr></table>
</body>
</html>