<? $url = $this->url(array('controller' => 'user', 'action' => 'new'), null, true) ?>
<a class="btn primary pull-right" href="<?= $url ?>">Add User</a>
<h2>Users</h2>

<table class="bordered-table zebra-striped">
    <? if (count($this->list)): ?>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Created At</th>
                <th>Operations</th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($this->list as $key => $item): ?>
                <tr>
                    <? $id = $item->id ?>
                    <td><?= $item->name ?> <?= $item->lastname ?></td>
                    <td><?= $item->email ?></td>
                    <td><?= $item->role ?></td>
                    <td><span title="<?= $item->created_at ?>"><?= $this->Hace($item->created_at) ?> ago</span></td>
                    <td>
                        <? $base = array('controller' => 'user', 'id' => $id) ?>

                        <? $url = $this->url($base + array('action' => 'edit'), null, true) ?>
                        <a href="<?= $url ?>"><span class="label notice">edit</span></a>

                        <? if ($item->active): ?>
                            <? $url = $this->url($base + array('action' => 'deactivate'), null, true) ?>
                            <a href="<?= $url ?>"><span class="label important">deactivate</span></a>
                        <? else: ?>
                            <? $url = $this->url($base + array('action' => 'activate'), null, true) ?>
                            <a href="<?= $url ?>"><span class="label success">activate</span></a>
                        <? endif; ?>
                    </td>
                </tr>
            <? endforeach; ?>
        </tbody>
    <? else: ?>
        <thead>
            <tr>
                <th>Not user yet :(</th>
            </tr>
        </thead>
        <tbody></tbody>
    <? endif; ?>
</table>